-- AlterTable
ALTER TABLE "Vehicle" ADD COLUMN     "loadFee" DOUBLE PRECISION NOT NULL DEFAULT 150,
ADD COLUMN     "minimumCharge" DOUBLE PRECISION NOT NULL DEFAULT 400,
ALTER COLUMN "baseRate" SET DEFAULT 250;
